// Area-agnostic real-world challenges (JetLag-style). One is assigned to each
// area at game start (cycling with a shuffle if there are more areas than
// challenges).
export const CHALLENGES: string[] = [
  "Order a drink in a language other than your default.",
  "Find and eat the spiciest item on any asian menu within reach.",
  "Find a food item priced under $1 and eat the whole thing.",
  "Assemble a sandwich where every filling starts with the same letter.",
  "Eat a full serving of the least popular item on a menu.",
  "Find and consume a drink that is an unusual color (blue, green, purple, etc.).",
  "Balance a snack on your forehead and get it into your mouth without hands.",
  "Walk exactly 1 kilometer (1 km) from where you stand, then measure it. Be within 10%.",
  "Estimate the perimeter of one city block, then measure it. Be within 15%.",
  "Get at least half a mile (800 m) from the nearest chain convenience store.",
  "Reach a point at least 100 feet (30 m) higher in elevation than your start, on foot.",
  "Travel three stops on public transit in any direction.",
  "Find the highest publicly accessible point in the district and take a photo.",
  "Find the oldest structure you can and verify its age within 50 years. Reattempt with another structure if missed.",
  "Recite a poem or sing a song in a public square.",
  "Get a passing car to honk using only a handmade sign held at a roadside.",
  "Paint or draw the view in front of you using at least 3 colors, covering most of the paper.",
  "Write a haiku about your current location and read it aloud.",
  "Build a small freestanding structure from found or bought materials, at least 1 foot (30 cm) tall.",
  "Fold a paper airplane and throw it 20 consecutive feet (6 m) in a park or square.",
  "Spell your first name using letters found in signs, graffiti, or storefronts.",
  "Catch three different species of insect (release them after).",
  "Photograph three different birds.",
  "Identify 5 different plants using a plant-ID app.",
  "Locate a piece of public art and share three things you notice about it.",
  "Find something older than 100 years and prove its age.",
  "Spot a license plate from another region or country.",
  "Find a flag from a country other than the one you're in.",
  "Find the district's #1 attraction (per reviews) and get within 500 feet (150 m) of it.",
  "Get a coin to land the same side up 5 times in a row.",
  "Roll a die; do that number times ten squats in a park (rest between sets as needed).",
  "Roll a ball into a cup from 10 feet (3 m) away in a park or open square.",
  "Land a plastic bottle upright on its base after tossing it.",
  "Throw an object into a container from 6 feet (1.8 m) away.",
  "Buy a scratch-off lottery ticket and reveal it on camera.",
  "Toss a piece of food and have a bird or animal eat it within 30 seconds.",
  "Guess the flavor of three mystery candies while blindfolded.",
  "Do 50 squats (thighs to parallel) in a public park; rest as needed.",
  "Do 30 push-ups on a park bench or lawn in as few sets as you like.",
  "Climb something safe at least 4 feet (1.2 m) off the ground in a park or playground.",
  "Walk 100 feet (30 m) in a square balancing an object on your head without dropping it.",
  "Carry a full cup of water a quarter mile (400 m) through a park without spilling more than 10%.",
  "Hold a plank for 90 seconds in a public square.",
  "Transfer 20 grains of rice one at a time between cups with chopsticks on a park bench.",
  "Pick up 10 separate pieces of litter in a park or street and dispose of them properly.",
  "Spend exactly a round number (e.g., $10.00) in one transaction, tax included.",
  "Purchase an item, then find the same item cheaper at another store.",
  "Mail a postcard to yourself.",
  "Buy a small stuffed animal or figurine, name it, and keep it for the rest of the game.",
  "Wear an item of clothing bought secondhand for the rest of the day.",
];
