// Generic, area-agnostic real-world challenges. One is assigned to each area at
// game start (cycling with a shuffle if there are more areas than challenges).
// Kept family-friendly and doable on foot in any neighbourhood.
export const CHALLENGES: string[] = [
  "Take a team selfie in front of the most eye-catching building in this area.",
  "Find and photograph a piece of street art, a mural, or graffiti.",
  "Photograph a street sign and read the street name aloud on camera.",
  "Find a bench and record a 5-second clip of the whole team sitting on it.",
  "Photograph something the colour of your team.",
  "Buy or find something and photograph the receipt or item with a local shop behind it.",
  "Find an animal (pet, bird, or statue of one) and get it in a photo.",
  "Photograph the oldest-looking building you can find here.",
  "Do a team jump and capture everyone mid-air in one photo.",
  "Find a map or public transport sign and photograph it.",
  "Photograph a door that is not white or brown.",
  "Ask a local for a fun fact about the area and record it (with consent).",
  "Find water — a fountain, river, puddle, or tap — and photograph it.",
  "Photograph a number higher than 50 written somewhere in the area.",
  "Find a tree taller than the whole team stacked up and photograph it.",
  "Photograph a vehicle with a colour that matches your team colour.",
  "Find a place to eat and photograph its sign or menu.",
  "Recreate a statue's pose and photograph the match.",
  "Photograph something that makes a sound, then describe the sound on camera.",
  "Find the highest point you can safely reach and photograph the view.",
  "Photograph a bicycle or a bike rack.",
  "Find a plaque or historical marker and photograph its text.",
  "Photograph a window with something interesting behind it.",
  "Find a set of stairs and film the team walking up them.",
  "Photograph a flag of any kind.",
  "Find something round bigger than your head and photograph it.",
  "Photograph a bin/trash can — bonus if it matches your team colour.",
  "Find a business that has been open (guess) more than 10 years; photograph it.",
  "Photograph the smallest door you can find.",
  "Find a mailbox or post box and photograph it.",
  "Photograph a reflection of the team in a window or puddle.",
  "Find a clock in public and photograph the time it shows.",
  "Photograph a plant growing somewhere it shouldn't.",
  "Find a place name that is hard to pronounce and say it on camera.",
  "Photograph two of the team doing a high-five in a doorway.",
  "Find a light that is on during the day and photograph it.",
  "Photograph a sign with an arrow and follow it 20 steps.",
  "Find a pattern (tiles, bricks, fence) and photograph a close-up.",
  "Photograph the team pointing at something tall.",
  "Find a shop selling food you have never tried; photograph it.",
  "Photograph a manhole cover or drain.",
  "Find something wooden and something metal in one photo.",
  "Photograph a corner where two streets meet, with both signs visible.",
  "Find a bus stop or station and photograph its name.",
  "Photograph the team making the same silly face.",
  "Find graffiti-free wall and take a clean team photo against it.",
  "Photograph something that is broken but still in use.",
  "Find the busiest spot in the area and film 5 seconds of it.",
  "Photograph a hand-written sign (not printed).",
  "Find a spot with an echo and shout your team name.",
];
