// Area-agnostic real-world challenges (JetLag-style). One is assigned to each
// area at game start (cycling with a shuffle if there are more areas than
// challenges).
export const CHALLENGES: string[] = [
  "Find and eat the spiciest item on any Asian menu within reach.",
  "Find a food item priced under $1 and eat the whole thing.",
  "Assemble a sandwich where every filling starts with the same letter. Use at least 3 fillings.",
  "Eat a full serving of the least popular item on a menu.",
  "Find and consume a drink that is an unusual color (blue, green, purple, etc.).",
  "Balance a snack on your forehead and get it into your mouth without hands.",
  "Eat one serving of the national dessert.",
  "Eat one serving of the national dish.",
  "Buy the local paper and solve one of its puzzles.",
  "Spend exactly a round number (e.g., $10.00) in one transaction, tax included.",
  "Run a mile [1.6 km] under 15 min, eating a pastry each quarter mile [400 m].",
  "Make mayonnaise (1 tbsp emulsified).",
  "Toss a piece of food and have a bird or animal eat it within 30 seconds.",
  "Guess the flavor of three mystery candies while blindfolded.",
  "Walk exactly 1 km from where you stand, then measure it — within 10%.",
  "Estimate the perimeter of one city block, then measure it — within 15%.",
  "Spin, point, and travel ~1 mile [1.6 km] in that direction.",
  "Get at least half a mile [800 m] from the nearest chain convenience store.",
  "Reach a point at least 100 ft [30 m] higher in elevation than your start, on foot.",
  "Ascend 3 meters [10 ft].",
  "Travel three stops on public transit in any direction.",
  "Find the highest publicly accessible point in the district and take a photo.",
  "Find the district's #1 attraction (per reviews) and get there.",
  "Paint or draw the view in front of you (3+ colors, covering ~75% of A4, min. 15 min).",
  "Write a haiku about your current location and read it aloud.",
  "Recite a poem or sing a song in a public square.",
  "Get a passing car to honk using only a handmade sign held at a roadside.",
  "Build a 2 ft [60 cm] freestanding spaghetti tower that holds for 10 sec.",
  "Build a small freestanding structure from found or bought materials, at least 1 ft [30 cm] tall.",
  "Fold and throw a paper airplane 20 consecutive feet [6 m] in a park or square.",
  "Cut an orange in half using only a plastic card.",
  "Move 30 grains of rice one at a time with chopsticks (or regular sticks).",
  "Transfer 20 grains of rice one at a time between cups with chopsticks on a park bench.",
  "Roll a ball into a cup from 10 ft [3 m] away in a park or open square.",
  "Land a plastic bottle upright on its base after tossing it.",
  "Throw an object into a container from 6 ft [1.8 m] away.",
  "Hit a target with a bow from 15 ft [4.5 m] (bow can be hand-made).",
  "Catch three different species of insect (release them after).",
  "Photograph three different birds.",
  "Film a single bird continuously for 5 min.",
  "Identify 5 different plants using a plant-ID app.",
  "Find and film yourself in front of a €50,000+ car.",
  "Spell your first name using letters found in signs, graffiti, or storefronts.",
  "Locate a piece of public art and share three things you notice about it.",
  "Find something older than 100 years and prove its age.",
  "Find the oldest structure you can and verify its age within 50 years (reattempt with another if missed).",
  "Spot a license plate from another region or country.",
  "Find a flag from a country other than the one you're in.",
  "Do 50 squats (thighs to parallel) in a public park; rest as needed.",
  "Roll a die; do that number × ten squats in a park (rest between sets).",
  "Do 30 push-ups on a park bench or lawn in as few sets as you like.",
  "Climb something safe at least 4 ft [1.2 m] off the ground in a park or playground.",
  "Walk 100 ft [30 m] balancing an object on your head without dropping it.",
  "Carry a full cup of water a quarter mile [400 m] through a park, spilling <10%.",
  "Hold a plank for 90 seconds in a public square; rest as needed.",
  "Pick up 10 separate pieces of litter in a park or street and dispose of them properly.",
  "Get a coin to land the same side up 5 times in a row.",
  "Buy a scratch-off lottery ticket and reveal it on camera.",
  "Win a prize from a claw machine or any casino game.",
  "Purchase an item, then find the same item cheaper at another store.",
  "Mail a postcard to yourself.",
  "Buy a small stuffed animal or figurine, name it, and keep it for the rest of the game.",
  "Wear an item of clothing bought secondhand for the rest of the day.",
];

// Extra challenges that require two teammates. Added to the pool only when the
// host sets a team size of 2 players.
export const TEAMMATE_CHALLENGES: string[] = [
  "Give your teammate a piggyback ride around a park's perimeter.",
  "Make a 30-second parkour video featuring both teammates.",
  "Find a Just Dance YouTube video. Make a 30-second video of you dancing it together.",
  "Communicate by Morse: stand 20 ft [6 m] apart, one signals an 8-letter word, the other decodes it.",
  "Be familiar with your teammate's pace: one runs to a spot 250–500 ft [75–150 m] away, the other predicts the time within 15%. If failed, repeat after 5 minutes. No practice.",
  "Buy the same thing as your teammate: one buys an item, the blindfolded partner inspects it then buys the same.",
  "Distinguish wines blindfolded: one partner buys 3 wines, the blindfolded partner identifies each.",
  "Identify chocolates blindfolded: one buys filled chocolates, the partner outside guesses each filling.",
  "Taste-test local foods: one feeds 3 items in one bite to the blindfolded partner, who identifies which 3.",
  "One teammate secretly draws a landscape for 3 minutes; afterward, the other names 10 things that must be in the drawing.",
  "Stand at least 20 ft [6 m] apart in a park and communicate a random 6-letter word using only hand signals; one guess, retry with a new word if wrong.",
  "Stand 30 ft [9 m] apart in a square and toss a soft object back and forth 10 times in a row without dropping it.",
  "One teammate hides a small object within a 50 ft [15 m] radius in a park; the other has 1 minute to find it using only \"warmer/colder\" calls.",
  "Balance a stick or pole horizontally between your two index fingers and walk 50 ft [15 m] in a plaza without it falling.",
  "Both teammates hold a plank at the same time in a public square for 90 seconds.",
];

/**
 * The default challenge pool for a given team size. Two-player teams get the
 * base pool plus the teammate-only challenges.
 */
export function defaultChallengePool(teamSize: number): string[] {
  return teamSize >= 2 ? [...CHALLENGES, ...TEAMMATE_CHALLENGES] : [...CHALLENGES];
}
